apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci-proyecto1-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/RichieQuintana/infra-proyecto-CI.git
    targetRevision: main
    path: k8s/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
